import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Happy Birthday Pangu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <div className={styles.birthdayGift}>
          <div className={styles.gift}>
            <label className={styles.click} for="click"></label>
            <div className={styles.wishes}>Happy Birthday!</div>
            <div className={styles.sparkles}></div>
            <div className={styles.spark1}></div>
            <div className={styles.spark2}></div>
            <div className={styles.spark3}></div>
            <div className={styles.spark4}></div>
            <div className={styles.spark5}></div>
            <div className={styles.spark6}></div>
          </div>
        </div>
      </main>
    </div>
  );
}
